variable "env" {}
variable "vpc_cidr_block" {}
variable "web_subnet_cidr" {}
variable "app_subnet_cidr" {}
variable "db_subnet_cidr" {}
variable "tags" {}
variable "azs" {}
variable "default_vpc_id" {}
variable "default_vpc_cidr" {}
variable "default_vpc_rt" {}
